<a href="https://colab.research.google.com/github/Ptmahayana/Pertemuan1_structure_dataD/blob/main/LatihanPraktikum1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Matrix 3x3 & Tampilkan Nilai Tengah Matrix**

In [3]:
import numpy as np
print("Matrix 3x3")
matrix = np.array ([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print(matrix)
print("Elemmen Tengah Matrix", matrix[1,1])

Matrix 3x3
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Elemmen Tengah Matrix 5


**Hitung Jumlah Nilai Seluruh Elemen Matrix**

In [4]:
import numpy as np
print("Hitung Jumlah seluruh elemen matrix")
jumlah_elemen = np.sum(matrix)
print("Jumlah seluruh elemen matrix adalah", jumlah_elemen)


Hitung Jumlah seluruh elemen matrix
Jumlah seluruh elemen matrix adalah 45


**Tabel Nilai x3 Mahasiswa X4 Matkul**

In [6]:
import numpy as np
print("Tabel Nilai Mahasiswa:")
nilai_mahasiswa = np.array ([[85, 90, 78, 92],
                             [88, 95, 80, 91],
                             [89, 94, 87, 93]])

print("Nilai Mahasiswa", nilai_mahasiswa)

Tabel Nilai Mahasiswa:
Nilai Mahasiswa [[85 90 78 92]
 [88 95 80 91]
 [89 94 87 93]]
